In [4]:
import numpy as np

## Numpy arrays!

In [5]:
listhere = [2,3,4,67]

In [10]:
np.array(listhere)

array([ 2,  3,  4, 67])

In [15]:
list2 = [[1,2], [4,5], [3,4]]
np.array(list2)

array([[1, 2],
       [4, 5],
       [3, 4]])

### Numpys built-in methods

In [16]:
np.arange(1,23,4)

array([ 1,  5,  9, 13, 17, 21])

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

**can pass a list or tuple to the zeros method**

In [26]:
np.zeros([3,4]) # 2D array here

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
np.linspace(3,11,30) # returns 30 equidistant values btw 3 and 11
# the result here is a 1D array (not 2D), watch the number of square braces

array([ 3.        ,  3.27586207,  3.55172414,  3.82758621,  4.10344828,
        4.37931034,  4.65517241,  4.93103448,  5.20689655,  5.48275862,
        5.75862069,  6.03448276,  6.31034483,  6.5862069 ,  6.86206897,
        7.13793103,  7.4137931 ,  7.68965517,  7.96551724,  8.24137931,
        8.51724138,  8.79310345,  9.06896552,  9.34482759,  9.62068966,
        9.89655172, 10.17241379, 10.44827586, 10.72413793, 11.        ])

### identity matrix

In [28]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [29]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [30]:
np.random.rand(5)  # rand sub method 

array([0.22900871, 0.02232669, 0.63233239, 0.29782568, 0.51849472])

In [34]:
np.random.rand(2,3) # random values

array([[0.57527508, 0.59046561, 0.06586923],
       [0.46750515, 0.98660935, 0.53524919]])

In [36]:
np.random.randn(2,3) # random values from standard normal distribution

array([[ 0.21684642,  1.10725374, -0.61396599],
       [ 1.99593524, -1.32841359, -1.19010112]])

In [37]:
np.random.randint(3,67,12) # returns 12 random integers btw 3 and 67; includes 12, excludes 67

array([56, 20, 43, 60, 30, 31, 30, 18, 31, 13, 15, 65])

### methods for arrays

In [38]:
arr = np.arange(2,34) # picking range of numbers

In [39]:
arr  # 1D array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

In [55]:
intarr = np.random.randint(2,34,32) # generating random numbers

In [56]:
intarr # 1D array

array([11,  9,  8, 16, 22, 17,  4, 16, 23,  6, 20, 27, 15, 32, 13, 30, 30,
       29,  2, 20, 31, 27, 15, 20, 25,  5, 17, 11, 18, 25, 32,  8])

In [52]:
arr.reshape(8,4) # array has 32 elements, reshaping into 8*4 ; 2D array

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25],
       [26, 27, 28, 29],
       [30, 31, 32, 33]])

In [48]:
arr.reshape(2,16) # array has 32 elements, reshaping into 2*16

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33]])

In [57]:
intarr.max() # returns max value

32

In [59]:
intarr.argmax() # index at which max value 32 is present - 13

13

In [60]:
intarr.shape

(32,)

In [61]:
intarr.dtype

dtype('int64')

In [65]:
from numpy.random import randint

In [68]:
# can declare a submethod if being used a lot
arr2 = randint(2,11,44)

In [69]:
arr2

array([ 9,  9,  4,  3,  8,  6,  3,  3,  3,  2,  8,  6,  5,  4,  2,  2,  8,
        2,  2,  9,  7,  2, 10,  4,  4,  9, 10,  9,  9,  5,  4,  3,  2,  2,
        6,  4,  2,  5,  4, 10,  2, 10,  8,  8])

In [70]:
arr2.reshape(4,11)

array([[ 9,  9,  4,  3,  8,  6,  3,  3,  3,  2,  8],
       [ 6,  5,  4,  2,  2,  8,  2,  2,  9,  7,  2],
       [10,  4,  4,  9, 10,  9,  9,  5,  4,  3,  2],
       [ 2,  6,  4,  2,  5,  4, 10,  2, 10,  8,  8]])

## Numpy array indexing

In [71]:
import numpy as np

In [117]:
new_Array = np.arange(2,26)

In [105]:
new_Array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25])

In [106]:
new_Array[:] # indexing

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25])

In [107]:
newslice = new_Array[6:14]

In [108]:
newslice

array([ 8,  9, 10, 11, 12, 13, 14, 15])

### Array broadcasting

In [109]:
newslice[:]=82 # Array broascasting

In [110]:
newslice

array([82, 82, 82, 82, 82, 82, 82, 82])

In [111]:
new_Array # original array also got broadcasted by doing for the sliced array

array([ 2,  3,  4,  5,  6,  7, 82, 82, 82, 82, 82, 82, 82, 82, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25])

In [118]:
copy_new_array = new_Array.copy()

In [119]:
copy_new_array # to retain the original data 

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25])

In [113]:
new_Array

array([ 2,  3,  4,  5,  6,  7, 82, 82, 82, 82, 82, 82, 82, 82, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25])

### Indexing 2D array or Matrix

In [122]:
Array_2d = np.array(([2,3,7,2],[3,5,2,4],[9,4,98,23]))

In [131]:
Array_2d

array([[ 2,  3,  7,  2],
       [ 3,  5,  2,  4],
       [ 9,  4, 98, 23]])

In [124]:
Array_2d[2,3] # grabbing an element

23

In [126]:
Array_2d[1:,2:] # grabbing a portion of array (more than 1 element) aka array slicing

array([[ 2,  4],
       [98, 23]])

In [127]:
array1 = np.arange(1,21)

In [128]:
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [130]:
array1[array1>11] # conditional indexing; returns values > 11 in the array

array([12, 13, 14, 15, 16, 17, 18, 19, 20])

In [134]:
Array_2d[Array_2d>20] # taking the 2D array from above

array([98, 23])

### Exercise

In [135]:
t1array = np.arange(40).reshape(8,5)

In [136]:
t1array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [142]:
t1array[2:7,1:4] # grabbing 11 to 33

array([[11, 12, 13],
       [16, 17, 18],
       [21, 22, 23],
       [26, 27, 28],
       [31, 32, 33]])

### Numpy Operations